data_path: datasets/
LABEL_FIELD: label
benchmark_filename: ['train', 'valid', 'test']
dataset: 'dbbook'
checkpoint_dir: saved_dbbook/
model: 'KGIN'
epochs: 50
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10000
seed: 42

# Knowledge-aware models
# embedding_size: 32
# kg_embedding_size: 512
# ls_weight: 0.1
# margin: 0.8
# loss_function: transe
# mass_dropout: 0.1
# reg_weight: [0.1, 0.1]
# layers: [128]

#topk: 5

# SLIMElastic params
# alpha choice [0.2,0.5,0.8,1.0]
# l1_ratio choice [0.5,0.1]

# LightGCN params
# embedding_size choice [32, 64, 128]
# n_layers choice [1, 2, 3]